name: Espresso From Hell
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0e4f9ca4-6439-4b10-87ef-a648cf5f670f.jpg
layout_spectrum: 0.50073
typography_spectrum: 0.47785
title: Espresso From Hell - Electro-jazz from Switzerland
author:
  name: Pierre Sottas
  url: ''
  email: pierre.sottas@cheesecom.com
content_rating:
  adult: false
navigation:
  - name: The band
    id: fa1dda74-fde8-4b63-bfc9-3e0b1f340a72
    type: content
  - name: What guys say
    id: f6747690-a48e-4ef4-8832-e3156fb4feff
    type: content
  - name: Contact
    id: 8bc87754-9321-465b-a461-5509dab72181
    type: content
  - name: Presskit
    url: 'http://presskit.espressofromhell.com'
    type: external
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-58965710-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: ''
  appId: ''
color:
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
  brandStrength: 0.8279940381180495
  lightness: 0.875
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
