name: Espresso From Hell
favicon: null
layout_spectrum: 0.49908
typography_spectrum: 0.8324203521478921
title: Espresso From Hell - electro-jazz duo from Switzerland
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eae5ca'
    - '#b98f55'
    - '#765729'
    - '#aac3bc'
    - '#ccd3bf'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
