typography_spectrum: 0.28167
color:
  brandColors:
    - '#ece6cd'
    - '#bb8f53'
    - '#856433'
    - '#c4b497'
    - '#95b3a3'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.35883
analytics:
  google: UA-58965710-1
  facebook: null
  twitter: null
author:
  name: Pierre Sottas
  email: pierre.sottas@cheesecom.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cee599f1-9b32-48a3-ac39-d11b72deff33.jpg
name: Espresso From Hell
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Espresso From Hell - electro-jazz duo from Switzerland
purpose: []
