name: Espresso From Hell
favicon: null
layout_spectrum: 0.8497620376292616
typography_spectrum: 0.8324203521478921
title: Espresso From Hell - electro-jazz duo from Switzerland
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9145635389722884
  lightness: 0.8185225923079997
  saturation: 0.9240940571762621
  rhythmicContrast: 0.07955889473669231
purpose: []
