typography_spectrum: 0.30546314432285726
content_rating:
  adult: false
color:
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.3125
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: ''
  appId: ''
layout_spectrum: 0.49854
analytics:
  google: UA-58965710-2
  facebook: null
  twitter: null
author:
  name: Pierre Sottas
  url: ''
  email: pierre.sottas@cheesecom.com
name: Espresso From Hell
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Contact
    id: 8bc87754-9321-465b-a461-5509dab72181
    type: content
  - name: Presskit
    url: 'http://presskit.espressofromhell.com'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0e4f9ca4-6439-4b10-87ef-a648cf5f670f.jpg
title: Espresso From Hell
description: Electro-Jazz from Switzerland
purpose: []
