analytics: {}
color:
  brandColors:
    - '#ece6cd'
    - '#bb8f53'
    - '#856433'
    - '#c4b497'
    - '#95b3a3'
  brandStrength: 0.25
  lightness: 0.25
  rhythmicContrast: 0.5
  saturation: 0.5
cta: {}
layout_spectrum: 0.2447
name: Espresso From Hell
opengraph: {}
purpose: []
typography_spectrum: 0.787162
