typography_spectrum: 0.0786796158645302
color:
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
  brandStrength: 0.8279940381180495
  lightness: 0.8529976245481521
  saturation: 0.7605673484504223
  rhythmicContrast: 0.11492787254974246
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.05567360948771238
analytics:
  google: UA-58965710-2
  facebook: null
  twitter: null
author:
  name: Pierre Sottas
  email: pierre.sottas@cheesecom.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7399f78d-c1f1-421a-998e-1513fd50908a.jpg
name: Espresso From Hell
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: The band
    id: fa1dda74-fde8-4b63-bfc9-3e0b1f340a72
    type: content
  - name: Presskit
    url: 'http://presskit.espressofromhell.com'
    type: external
  - name: What guys say
    id: f6747690-a48e-4ef4-8832-e3156fb4feff
    type: content
  - name: Contact
    id: 8bc87754-9321-465b-a461-5509dab72181
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0e4f9ca4-6439-4b10-87ef-a648cf5f670f.jpg
title: Espresso From Hell
description: Electro-jazz duo from Switzerland
purpose: []
