name: Espresso From Hell
favicon: null
layout_spectrum: 0.49908
typography_spectrum: 0.74571
title: Espresso From Hell - electro-jazz duo from Switzerland
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ece6cd'
    - '#bb8f53'
    - '#856433'
    - '#c4b497'
    - '#95b3a3'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
